In [ ]:
print("Hello World!")

Hello World!


In [ ]:
# Variables
name = "Vartika" #STRING DATA TYPE
age = 25 # INT DATA TYPE
height = 5.4 # FLOAT DATA TYPE
is_student = True #BOOL DATA TYPE

print("Name:", name)
print("Age:", age)
print("Height:", height)
print("Is Student:", is_student)

Name: Vartika <class 'str'>
Age: 25
Height: 5.4
Is Student: True


In [ ]:
# Data Types

print("Name:", name,type(name))
print("Age:", age,type(age))
print("Height:", height,type(height))
print("Is Student:", is_student,  type(is_student))

Name: Vartika <class 'str'>
Age: 25 <class 'int'>
Height: 5.4 <class 'float'>
Is Student: True <class 'bool'>


In [ ]:
print("Coding "*5)

Coding Coding Coding Coding Coding 


In [ ]:
# program to print word "Coding" 5 time
print("Coding "*5)

Coding Coding Coding Coding Coding 


In [ ]:
'''
print following para:
hi
this is my 2nd python class
'''
print("hi")
print("this is my 2nd python class")

hi
this is my 2nd python class


In [ ]:
print("hi")
#print("this is my 2nd python class")

hi


In [ ]:
#print("hi")
print("this is my 2nd python class")

this is my 2nd python class


In [ ]:
x=15
print(x)

15


In [ ]:
y="fmt"
print(y)

fmt


In [ ]:
#add two no.
a=10
b=20
c=a+b
print("sum=",c)

sum= 30


In [ ]:
#arithmatic operation
print("addition:",a+b)
print("subtraction:",a-b)
print("multiplication:",a*b)
print("division:",a/b)
print("floor division:",a//b)
print("modulus:",a%b)
print("exponent:",a**b) #a to the power b

addition: 30
subtraction: -10
multiplication: 200
division: 0.5
floor division: 0
modulus: 10
exponent: 100000000000000000000


In [ ]:
#add two no.
a=int(input("enter first no."))
b=int(input("enter second no."))
c=a+b
print("sum=",c)

enter first no.9
enter second no.1
sum= 10


#  Basic Python Practice Questions
1. Write a program that takes 3 no.s as input, print the sum on them.
2. Write a program that takes lenght and height as input, print the area of rectangle.
3. Write a program that takes a number and prints its square and cube.
4. Write a program that takes two numbers and performs all arithmetic operations on them.
5. Write a program that takes marks of 3 subjects, calculates the total and average.
6. Write a program to calculate the area and circumference of a circle. (Take radius as input)
7. Write a program to calculate the simple interest (SI = P*R*T / 100).(Take P,R,T as input)
8.  Write a program to swap the values of two variables.

In [ ]:
# If-else – decision making
age=30
if age >= 18:#TRUE
    print("You are an adult")
else:
    print("You are a minor")

You are an adult


In [ ]:
# If-else – decision making
age=17
if age >= 18:#FALSE
    print("You are an adult")
else:
    print("You are a minor")

You are a minor


In [ ]:
#DETECT +VE AND -VE NO.
#NO. LINE ..., -3,-2, -1, 0, 1, 2, 3, ...
num=-9
if num > 0:
    print("positive")
else:
    print("negative")

negative


In [ ]:
#DETECT +VE AND -VE NO.
#NO. LINE ..., -3,-2, -1, 0, 1, 2, 3, ...
num=int(input("enter a no."))
if num > 0:
    print("positive")
else:
    print("negative")

enter a no.7
positive


In [ ]:
#check multiple condition
if age > 18:
    print("Adult")
elif age == 18:
    print("Just turned 18")
else:
    print("Minor")

In [ ]:
# List - ordered, changeable, allows duplicates
fruits = ["apple", "banana", "cherry"]
print(fruits)

['apple', 'banana', 'cherry']


In [ ]:
# Access item based on indexing
print(fruits[0])

apple


In [ ]:
# Add item
fruits.append("mango")
print(fruits)

['apple', 'banana', 'cherry', 'mango']


In [ ]:
# Tuple - ordered, unchangeable, allows duplicates
colors = ("red", "green", "blue")
print(colors)

('red', 'green', 'blue')


In [ ]:
# Access item
print(colors[0])

red


In [ ]:
# Set - unordered, no duplicate items
numbers = {1, 2, 3, 3, 2}
print(numbers)  # Output will be {1, 2, 3}

{1, 2, 3}


In [ ]:
# Add item
numbers.add(4)
print(numbers)

{1, 2, 3, 4}


In [ ]:
# Dictionary - key-value pairs
student = {
    "name": "Vartika",
    "age": 25,
    "course": "Python"
}

print(student)

{'name': 'Vartika', 'age': 25, 'course': 'Python'}


In [ ]:
# Access value
print(student["name"])

Vartika


In [ ]:
# Add key-value
student["grade"] = "A"
print(student)

{'name': 'Vartika', 'age': 25, 'course': 'Python', 'grade': 'A'}


In [ ]:
#LOOPS: Loops help you repeat tasks without writing the same code again and again.
# FOR LOOP

#  PRINT NAME 5 TIME: Loop from 0 to 4
for i in range(5):
    print("FMT")


FMT
FMT
FMT
FMT
FMT


In [ ]:
# Loop from 0 to 4
for i in range(5):
    print("Number:", i)

Number: 0
Number: 1
Number: 2
Number: 3
Number: 4


In [ ]:
# Loop from 1 to 4
for i in range(1,5):
    print("Number:", i)

Number: 1
Number: 2
Number: 3
Number: 4


In [ ]:
# Loop from 1 to 4
for i in range(1,10,2):
    print("Number:", i)

Number: 1
Number: 3
Number: 5
Number: 7
Number: 9


In [ ]:
#Loop through a list
fruits = ["apple", "banana", "mango"]
print(type(fruits))


<class 'list'>


In [ ]:
for i in fruits:
    print("I like", i)

I like apple
I like banana
I like mango


In [ ]:
for fruit in fruits:
    print("I like", fruit)

I like apple
I like banana
I like mango


In [ ]:
# while loop

count = 0
while count < 5:
    print("Count:", count)
    count += 1 # count = count + 1 #

Count: 0
Count: 1
Count: 2
Count: 3
Count: 4


In [ ]:

count = 1
while count < 5:
    print("Count:", count)
    count += 1 # count = count + 1 #

Count: 1
Count: 2
Count: 3
Count: 4


In [ ]:

count = 1
while count < 10:
    print("Count:", count)
    count += 2 # count = count + 1 #

Count: 1
Count: 3
Count: 5
Count: 7
Count: 9


In [ ]:
#Nested Loops : A loop inside another loop.

for i in range(2):  # Outer loop
    for j in range(3):  # Inner loop
        print("i:", i, "j:", j)

i: 0 j: 0
i: 0 j: 1
i: 0 j: 2
i: 1 j: 0
i: 1 j: 1
i: 1 j: 2


In [ ]:
#Nested Loops : A loop inside another loop.

for i in range(4):  # Outer loop
    for j in range(6):  # Inner loop
        print("*"*j*i)









*
**
***
****
*****

**
****
******
********
**********

***
******
*********
************
***************


In [ ]:
#Functions
def greet(person):
    print( "Hello, " + person + "!")
    print("How are you?")



In [ ]:
greet('anna')
greet('anna')
greet('anna')

Hello, anna!
How are you?
Hello, anna!
How are you?
Hello, anna!
How are you?


In [ ]:
greet("FMT")

Hello, FMT!
How are you?


In [ ]:
greet("FMT")

Hello, FMT!
How are you?


In [ ]:
#Lambda Functions:Anonymous (nameless) functions defined using the lambda keyword — used for short, simple functions.
square = lambda x: x ** 2
print(square(5))  # Output: 25

25


In [ ]:
square(10)

100

In [ ]:
add = lambda a, b: a + b
print(add(3, 4))  # Output: 7

7


In [ ]:
x = 1 / 0

ZeroDivisionError: division by zero

In [ ]:
#Error Handling

try:
    x = 1 / 0
    print(x)
except ZeroDivisionError:
    print("Cannot divide by zero")
finally:
    print("Done")

Cannot divide by zero
Done


In [ ]:
#File Handling

#Open a File and write

f = open("file.txt", "w")
f.write("This is a new file.")
f.close()
'''
'r' = read, 'w' = write, 'a' = append, 'x' = create  , 't' = text (default), 'b' = binary
'''

"\n'r' = read, 'w' = write, 'a' = append, 'x' = create  , 't' = text (default), 'b' = binary\n"

In [ ]:
#f = open("myfile.txt", "x")  # Creates a new file (error if exists)

In [ ]:
#. Open and Read File

f = open("file.txt", "r")  # Open in read mode
print(f.read())
f.close()

This is a new file.


In [ ]:
#With Statement (Auto close)
with open("file.txt", "r") as f:
    print(f.read())

This is a new file.


In [ ]:
#Check & Delete File
import os
os.path.exists("file.txt")     # check
os.remove("file.txt")          # delete

In [ ]:
import math

radius = 5
area = math.pi * math.pow(radius, 2) #r**2
print("Area of circle:", area)

Area of circle: 78.53981633974483


---

## 📘 Python `math` Module – Essential Functions

The `math` module in Python provides access to mathematical functions and constants. Below is a list of commonly used functions:

---

### 🔹 Mathematical Operations

- **`math.sqrt(x)`**  
  Returns the square root of `x`.  
  *Example:* `math.sqrt(16)` → `4.0`

- **`math.pow(x, y)`**  
  Returns `x` raised to the power of `y`.  
  *Example:* `math.pow(2, 3)` → `8.0`

- **`math.floor(x)`**  
  Rounds `x` down to the nearest whole number.  
  *Example:* `math.floor(3.9)` → `3`

- **`math.ceil(x)`**  
  Rounds `x` up to the nearest whole number.  
  *Example:* `math.ceil(3.1)` → `4`

- **`math.factorial(x)`**  
  Returns the factorial of `x`.  
  *Example:* `math.factorial(5)` → `120`

- **`math.gcd(x, y)`**  
  Computes the greatest common divisor of `x` and `y`.  
  *Example:* `math.gcd(12, 18)` → `6`

- **`math.fabs(x)`**  
  Returns the absolute value of `x` as a float.  
  *Example:* `math.fabs(-3.5)` → `3.5`

---

### 🔹 Logarithmic & Exponential

- **`math.log(x, base)`**  
  Returns the logarithm of `x` to the specified `base`.  
  *Example:* `math.log(100, 10)` → `2.0`

- **`math.exp(x)`**  
  Returns the value of *e* raised to the power `x` (e^x).  
  *Example:* `math.exp(2)` → `7.389`

---

### 🔹 Mathematical Constants

- **`math.pi`**  
  Returns the value of π (pi).  
  *Example:* `math.pi` → `3.1415...`

- **`math.e`**  
  Returns the value of Euler’s number *e*.  
  *Example:* `math.e` → `2.718...`

---


In [ ]:
#List Comprehensions: A concise way to create lists using a single line of code.
squares = [x**2 for x in range(5)]#0,1,2,3,5-1=4
# Output: [0, 1, 4, 9, 16]
squares


[0, 1, 4, 9, 16]

In [ ]:
even_nums = [x for x in range(10) if x % 2 == 0]
# Output: [0, 2, 4, 6, 8]
even_nums

[0, 2, 4, 6, 8]

## Data Analysis



---

## 📊 **Data Analysis – Quick Notes**

---

### ✅ **1. What is Data Analysis?**
Data Analysis is the process of **inspecting, cleaning, transforming, and modeling data** to discover useful insights, patterns, and support decision-making.

---

### ✅ **2. Key Steps in Data Analysis**
1. **Data Collection** – Gather data from multiple sources (CSV, databases, APIs, web scraping, etc.)
2. **Data Cleaning** – Handle missing values, remove duplicates, fix data types, outliers, etc.
3. **Data Exploration (EDA)** – Use statistics and visuals to understand data patterns.
4. **Data Transformation** – Feature engineering, normalization, encoding.
5. **Modeling & Analysis** – Apply machine learning or statistical models.
6. **Interpretation & Communication** – Present insights using reports, dashboards, or visualizations.

---

### ✅ **3. Commonly Used Libraries in Python**
- **NumPy** – Numerical computations
- **Pandas** – Data manipulation (Series, DataFrames)
- **Matplotlib / Seaborn** – Data visualization
- **Scikit-learn** – Machine learning & preprocessing
- **Statsmodels** – Statistical analysis

---

### ✅ **4. Important Pandas Functions**
- `pd.read_csv("file.csv")` – Load dataset  
- `df.head()` / `df.tail()` – View first/last rows  
- `df.info()` / `df.describe()` – Dataset summary  
- `df.isnull().sum()` – Missing value check  
- `df.dropna()` / `df.fillna(value)` – Handle missing values  
- `df.groupby("column")` – Group and aggregate  
- `df.sort_values("column")` – Sort data  

---

### ✅ **5. Exploratory Data Analysis (EDA)**
- **Univariate analysis** – Distribution of one variable (histogram, boxplot)
- **Bivariate analysis** – Relationships (scatter plot, correlation matrix)
- **Outliers** – Detected using boxplot or IQR
- **Correlation** – `df.corr()` helps detect multicollinearity

---

### ✅ **6. Data Visualization**
- `matplotlib.pyplot.plot()`, `.bar()`, `.hist()`, `.scatter()`
- `seaborn.heatmap()`, `sns.pairplot()`, `sns.boxplot()`

---

### ✅ **7. Descriptive Statistics**
- **Mean, Median, Mode**
- **Standard Deviation, Variance**
- **Percentiles, Quartiles**
- **Skewness & Kurtosis**

---


In [ ]:
#NumPy : 1d arr, 2d arr
import numpy as np



In [ ]:
#Creating Arrays
#               0  1  2  3
arr = np.array([1, 2, 3])  # 1D array
arr


array([1, 2, 3])

In [ ]:
arr_2d = np.array([[1, 2], [3, 4]])  # 2D array
arr_2d

array([[1, 2],
       [3, 4]])

In [ ]:
zeros = np.zeros((2, 2))  # 2x2 matrix of zeros
zeros


array([[0., 0.],
       [0., 0.]])

In [ ]:

ones = np.ones((2, 2))  # 2x2 matrix of ones
ones

array([[1., 1.],
       [1., 1.]])

In [ ]:
#Indexing & Slicing

arr[0]  # Access element

np.int64(1)

In [ ]:
#               0  1   2  3  4
arr = np.array([11,12, 3, 4, 5])  # 1D array
arr
arr[0:2]  # Slice array

array([11, 12])

In [ ]:

arr_2d[0, 1]  # 2D array access

np.int64(2)

In [ ]:
#Array Operations

result1 = arr + arr  # Element-wise addition
result2 = arr * arr  # Element-wise multiplication
dot_result = np.dot(arr, arr)  # Dot product

print(result1, result2, dot_result)

[22 24  6  8 10] [121 144   9  16  25] 315


In [ ]:
arr_2d

array([[1, 2],
       [3, 4]])

In [ ]:
transposed_arr = arr_2d.T
transposed_arr

array([[1, 3],
       [2, 4]])

In [ ]:
arr

array([1, 2, 3])

In [ ]:
mean = np.mean(arr)
mean

np.float64(2.0)

In [ ]:
sum_val = np.sum(arr)
sum_val

np.int64(6)

In [ ]:
min_val = np.min(arr)
min_val

np.int64(1)

In [ ]:
 #Broadcasting

arr + 5

array([6, 7, 8])

In [ ]:
#Random Module

rand_arr = np.random.rand(4, 3)
rand_arr

array([[0.4751517 , 0.02463159, 0.50876405],
       [0.45726544, 0.20902363, 0.45880409],
       [0.76999381, 0.96262717, 0.75022486],
       [0.86964579, 0.21350019, 0.44526446]])

In [ ]:

rand_int_arr = np.random.randint(-10, 10, (4, 3))
rand_int_arr

array([[-6, -7, -6],
       [ 7,  9, -7],
       [-8, -5,  5],
       [-6, -1,  3]])

In [ ]:
import pandas as pd
df=pd.read_csv('sales_data_sample.csv')
df

ORDERNUMBER  QUANTITYORDERED  PRICEEACH  ORDERLINENUMBER    SALES  \
0           10107               30      95.70                2  2871.00   
1           10121               34      81.35                5  2765.90   
2           10134               41      94.74                2  3884.34   
3           10145               45      83.26                6  3746.70   
4           10159               49     100.00               14  5205.27   
...           ...              ...        ...              ...      ...   
2818        10350               20     100.00               15  2244.40   
2819        10373               29     100.00                1  3978.51   
2820        10386               43     100.00                4  5417.57   
2821        10397               34      62.24                1  2116.16   
2822        10414               47      65.52                9  3079.44   

            ORDERDATE    STATUS  QTR_ID  MONTH_ID  YEAR_ID  ...  \
0      2/24/2003 0:00   Shipped       1         2     2003  ...   
1     05-07-2003 0.00   Shipped       2         5     2003  ...   
2     07-01-2003 0.00   Shipped       3         7     2003  ...   
3      8/25/2003 0:00   Shipped       3         8     2003  ...   
4     10-10-2003 0.00   Shipped       4        10     2003  ...   
...               ...       ...     ...       ...      ...  ...   
2818  12-02-2004 0.00   Shipped       4        12     2004  ...   
2819   1/31/2005 0:00   Shipped       1         1     2005  ...   
2820  03-01-2005 0.00  Resolved       1         3     2005  ...   
2821   3/28/2005 0:00   Shipped       1         3     2005  ...   
2822  05-06-2005 0.00   On Hold       2         5     2005  ...   

                       ADDRESSLINE1  ADDRESSLINE2           CITY STATE  \
0           897 Long Airport Avenue           NaN            NYC    NY   
1                59 rue de l'Abbaye           NaN          Reims   NaN   
2     27 rue du Colonel Pierre Avia           NaN          Paris   NaN   
3                78934 Hillside Dr.           NaN       Pasadena    CA   
4                   7734 Strong St.           NaN  San Francisco    CA   
...                             ...           ...            ...   ...   
2818             C/ Moralzarzal, 86           NaN         Madrid   NaN   
2819                    Torikatu 38           NaN           Oulu   NaN   
2820             C/ Moralzarzal, 86           NaN         Madrid   NaN   
2821          1 rue Alsace-Lorraine           NaN       Toulouse   NaN   
2822             8616 Spinnaker Dr.           NaN         Boston    MA   

     POSTALCODE  COUNTRY TERRITORY CONTACTLASTNAME CONTACTFIRSTNAME DEALSIZE  
0         10022      USA       NaN              Yu             Kwai    Small  
1         51100   France      EMEA         Henriot             Paul    Small  
2         75508   France      EMEA        Da Cunha           Daniel   Medium  
3         90003      USA       NaN           Young            Julie   Medium  
4           NaN      USA       NaN           Brown            Julie   Medium  
...         ...      ...       ...             ...              ...      ...  
2818      28034    Spain      EMEA          Freyre            Diego    Small  
2819      90110  Finland      EMEA       Koskitalo           Pirkko   Medium  
2820      28034    Spain      EMEA          Freyre            Diego   Medium  
2821      31000   France      EMEA          Roulet          Annette    Small  
2822      51003      USA       NaN         Yoshido             Juri   Medium  

[2823 rows x 25 columns]